# Generated by Django 2.2.17 on 2021-07-07 16:24

from django.db import migrations, models
import toolhub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toollist',
            options={'verbose_name': 'toollist'},
        ),
        migrations.AddField(
            model_name='toollist',
            name='tool_names',
            field=toolhub.fields.JSONSchemaField(blank=True, default=list, help_text='List of the names of the tools in this list.'),
        ),
        migrations.AlterField(
            model_name='toollist',
            name='favorites',
            field=models.BooleanField(default=False, help_text="If true, this list is a collection of the owning user's 'favorite' tools."),
        ),
    ]
