# Generated by Django 2.2.17 on 2021-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_add_tool_names'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='toollist',
            constraint=models.UniqueConstraint(condition=models.Q(favorites=True), fields=('created_by',), name='unique_favorites_user'),
        ),
        migrations.AddConstraint(
            model_name='toollistitem',
            constraint=models.UniqueConstraint(fields=('toollist', 'tool'), name='unique_item'),
        ),
    ]
