# Generated by Django 2.2.17 on 2021-01-27 20:35

from django.db import migrations
from django.db import models

class AddRemoteField(migrations.AddField):
    """From https://stackoverflow.com/a/27160571/8171"""
    def __init__(self, remote_app, *args, **kwargs):
        super(AddRemoteField, self).__init__(*args, **kwargs)
        self.remote_app = remote_app

    def state_forwards(self, app_label, *args, **kwargs):
        super(AddRemoteField, self).state_forwards(
            self.remote_app, *args, **kwargs)

    def database_forwards(self, app_label, *args, **kwargs):
        super(AddRemoteField, self).database_forwards(
            self.remote_app, *args, **kwargs)

    def database_backwards(self, app_label, *args, **kwargs):
        super(AddRemoteField, self).database_backwards(
            self.remote_app, *args, **kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ("toolinfo", "0004_jsonschemafield"),
        ("reversion", "0001_squashed_0004_auto_20160611_1202"),
    ]

    operations = [
        # HACK! Add monkey patched field to reversion_version
        AddRemoteField(
            remote_app="reversion",
            model_name="version",
            name="suppressed",
            field=models.BooleanField(blank=True, default=False, db_index=True),
            preserve_default=True,
        ),
    ]
