# Generated by Django 2.2.17 on 2021-02-03 01:52

from django.db import migrations, models
import toolhub.apps.toolinfo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0005_monkey_patch_reversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='license',
            field=models.CharField(blank=True, help_text="The software license the tool code is available under. Use a standard SPDX license identifier like 'GPL-3.0-or-later'.", max_length=255, null=True, validators=[toolhub.apps.toolinfo.validators.validate_spdx]),
        ),
    ]
