# Generated by Django 2.2.17 on 2021-02-05 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0006_spdx_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='icon',
            field=models.CharField(blank=True, help_text='A link to a Wikimedia Commons file description page for an icon that depicts the tool.', max_length=2047, null=True, validators=[django.core.validators.RegexValidator(regex='^https://commons\\.wikimedia\\.org/wiki/File:.+\\..+$')]),
        ),
    ]
