# Generated by Django 2.2.17 on 2021-02-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0007_fix_icon_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
