# Generated by Django 2.2.17 on 2021-03-16 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0008_T274018_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='api_url',
            field=models.TextField(blank=True, help_text="A link to the tool's API, if available.", max_length=2047, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='bugtracker_url',
            field=models.TextField(blank=True, help_text="A link to the tool's bug tracker on GitHub, Bitbucket, Phabricator, etc.", max_length=2047, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='replaced_by',
            field=models.TextField(blank=True, help_text='If this tool is deprecated, this parameter should be used to link to the replacement tool.', max_length=2047, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='translate_url',
            field=models.TextField(blank=True, help_text="A link to the tool's translation interface.", max_length=2047, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.CharField(help_text='A direct link to the tool or to instructions on how to use or install the tool.', max_length=2047, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
