# Generated by Django 2.2.17 on 2021-03-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0009_url_validation_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
