# Generated by Django 2.2.17 on 2021-04-07 21:23

from django.db import migrations
import toolhub.apps.toolinfo.validators
import toolhub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0011_blankasnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='_language',
            field=toolhub.fields.BlankAsNullCharField(blank=True, help_text='The language in which this toolinfo record is written. If not set, the default value is English. Use ISO 639 language codes.', max_length=16, null=True, validators=[toolhub.apps.toolinfo.validators.validate_language_code]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='available_ui_languages',
            field=toolhub.fields.JSONSchemaField(blank=True, default=list, help_text="The language(s) the tool's interface has been translated into. Use ISO 639 language codes like `zh` and `scn`. If not defined it is assumed the tool is only available in English.", validators=[toolhub.apps.toolinfo.validators.validate_language_code_list]),
        ),
    ]
