# Generated by Django 2.2.24 on 2022-01-14 20:30

from django.db import migrations
import toolhub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0014_auto_20211125_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='author',
            field=toolhub.fields.JSONSchemaField(blank=True, default=list, help_text='The primary tool developers.'),
        ),
    ]
