# Generated by Django 2.2.24 on 2022-01-14 20:48

from django.db import migrations


def author_to_array(apps, schema_editor):
    """Convert legacy author string values to array format."""
    Tool = apps.get_model("toolinfo", "Tool")
    for tool in Tool.objects.all():
        was = tool.author
        if isinstance(was, str):
            tool.author = [
                {"name": name.strip()} for name in was.split(",")
            ]
            tool.save()

def array_to_author(apps, schema_editor):
    """Convert array format to string."""
    Tool = apps.get_model("toolinfo", "Tool")
    for tool in Tool.objects.all():
        tool.author = ", ".join(author["name"] for author in tool.author)
        tool.save()

class Migration(migrations.Migration):

    dependencies = [
        ("toolinfo", "0015_author_to_jsonschema"),
    ]

    operations = [
        migrations.RunPython(author_to_array, array_to_author),
    ]
