# Generated by Django 2.2.24 on 2022-01-19 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
#BUG(django-prometheus/issues/42) import django_prometheus.models
import toolhub.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toolinfo', '0016_author_convert_legacy_to_jsonschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='toolinfo.Tool')),
                ('wikidata_qid', toolhub.fields.BlankAsNullCharField(help_text='Wikidata item ID for the tool.', max_length=32, null=True, validators=[django.core.validators.RegexValidator(regex='^Q\\d+$')])),
            ],
            options={
                'abstract': False,
            },
            #BUG(django-prometheus/issues/42) bases=(django_prometheus.models.Mixin, models.Model),
        ),
    ]
