# Generated by Django 2.2.24 on 2022-01-19 22:54

from django.db import migrations


def backfill_annotations(apps, schema_editor):
    """Create an Annnotations instance for each Tool."""
    Tool = apps.get_model("toolinfo", "Tool")
    Annotations = apps.get_model("toolinfo", "Annotations")
    for tool in Tool.objects.all():
        Annotations.objects.create(tool=tool)


def clear_annotations(apps, schema_editor):
    """Remove Annnotations from all Tools."""
    Tool = apps.get_model("toolinfo", "Tool")
    for tool in Tool.objects.all():
        tool.annotations = None
        tool.save()


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0017_annotations'),
    ]

    operations = [
        migrations.RunPython(backfill_annotations, clear_annotations)
    ]
