# Generated by Django 3.2.13 on 2022-05-16 11:03

from django.db import migrations
import toolhub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0019_annotations_over_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='repository',
            field=toolhub.fields.BlankAsNullCharField(blank=True, help_text='A link to the repository where the tool code is hosted.', max_length=2047, null=True),
        ),
    ]
