# Generated by Django 3.2.13 on 2022-11-07 21:46

from django.db import migrations
import toolhub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0020_repository_to_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='audiences',
            field=toolhub.fields.JSONSchemaField(blank=True, default=list, help_text='Who is the intended user of the tool?'),
        ),
        migrations.AddField(
            model_name='annotations',
            name='content_types',
            field=toolhub.fields.JSONSchemaField(blank=True, default=list, help_text='With what type of content or data does the tool interact?'),
        ),
        migrations.AddField(
            model_name='annotations',
            name='subject_domains',
            field=toolhub.fields.JSONSchemaField(blank=True, default=list, help_text='Is the tool targeted at helping in a specific type of wiki project or topic area?'),
        ),
        migrations.AddField(
            model_name='annotations',
            name='tasks',
            field=toolhub.fields.JSONSchemaField(blank=True, default=list, help_text='What type of task does the tool help with?'),
        ),
    ]
