# Generated by Django 2.2.17 on 2021-06-07 19:52

from django.db import migrations, models
import django.db.models.deletion

from reversion.models import Version

from toolhub.apps.toolinfo.models import Tool
from toolhub.apps.versioned.models import RevisionMetadata


def backfill_metadata(apps, schema_editor):
    """Backfill RevisionMetadata models for existing Tool revisions."""
    qs = Version.objects.get_for_model(Tool)
    for ver in qs:
        meta = RevisionMetadata.objects.create(
            revision=ver.revision,
            suppressed=getattr(ver, "suppressed", False),
            patrolled=False,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionMetadata',
            fields=[
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='meta', serialize=False, to='reversion.Revision')),
                ('suppressed', models.BooleanField(db_index=True, default=False, help_text='Has this revision been marked as hidden?')),
                ('patrolled', models.BooleanField(db_index=True, default=False, help_text='Has this revision been reviewed by a patroller?')),
            ],
        ),
        migrations.RunPython(backfill_metadata, migrations.RunPython.noop),
    ]
