# Generated by Django 2.2.17 on 2020-12-01 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name': 'auditlog entry', 'verbose_name_plural': 'auditlog entries'},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.RenameField(
            model_name='logentry',
            old_name='action_time',
            new_name='timestamp',
        ),
    ]
