# Generated by Django 2.2.17 on 2021-01-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_rename_action_time_to_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (1, 'updated'), (2, 'deleted')], db_index=True, verbose_name='action'),
        ),
    ]
