# Generated by Django 2.2.17 on 2021-06-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0003_action_tense_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (1, 'updated'), (2, 'deleted'), (3, 'added to'), (4, 'removed from'), (5, 'hid'), (6, 'revealed')], db_index=True, verbose_name='action'),
        ),
    ]
