# Generated by Django 2.2.17 on 2021-06-09 16:46

from django.db import migrations, models
import toolhub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0004_add_hide_reveal'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='params',
            field=toolhub.fields.JSONSchemaField(null=True, default=dict),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (1, 'updated'), (2, 'deleted'), (3, 'added to'), (4, 'removed from'), (5, 'hid'), (6, 'revealed'), (7, 'patrolled')], db_index=True, verbose_name='action'),
        ),
    ]
