# Generated by Django 2.2.17 on 2020-11-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0001_initial'),
        ('crawler', '0002_auto_20201027_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('new_tools', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlerRunUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField()),
                ('redirected', models.BooleanField(default=False)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('schema', models.CharField(blank=True, max_length=32, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.CrawlerRun')),
                ('tools', models.ManyToManyField(related_name='runs', to='toolinfo.Tool')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawls', to='crawler.CrawledUrl')),
            ],
        ),
        migrations.AddField(
            model_name='crawlerrun',
            name='urls',
            field=models.ManyToManyField(through='crawler.CrawlerRunUrl', to='crawler.CrawledUrl'),
        ),
    ]
