# Generated by Django 2.2.17 on 2020-11-19 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawler', '0003_crawler_runs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawledUrl',
            new_name='Url',
        ),
        migrations.RemoveField(
            model_name='crawlerrun',
            name='urls',
        ),
        migrations.AlterField(
            model_name='crawlerrunurl',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='crawler.CrawlerRun'),
        ),
        migrations.AlterField(
            model_name='crawlerrunurl',
            name='tools',
            field=models.ManyToManyField(related_name='crawer_runs', to='toolinfo.Tool'),
        ),
        migrations.AlterField(
            model_name='crawlerrunurl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_runs', to='crawler.Url'),
        ),
    ]
