# Generated by Django 2.2.17 on 2020-11-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolinfo', '0001_initial'),
        ('crawler', '0004_rename_crawledurl_to_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrawlerRun',
            new_name='Run',
        ),
        migrations.RenameModel(
            old_name='CrawlerRunUrl',
            new_name='RunUrl',
        ),
    ]
