# Generated by Django 2.2.17 on 2020-12-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_remove_modified_from_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='total_tools',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='updated_tools',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
