# Generated by Django 2.2.17 on 2021-02-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_run_add_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
