# Generated by Django 2.2.17 on 2021-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_T274018_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='runurl',
            name='logs',
            field=models.TextField(blank=True),
        ),
    ]
