---
services:
  oauth-client:
    build:
      context: .
      dockerfile: .pipeline/blubber.yaml
      target: oauth-client
    image: "toolhub:oauth-client"
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - SECRET_KEY
      - TOOLHUB_CLIENT_ID
      - TOOLHUB_CLIENT_SECRET
      - TOOLHUB_ACCESS_TOKEN_URL
      - TOOLHUB_AUTHORIZE_URL
      - TOOLHUB_API_BASE_URL
    ports:
      - "${TOOLHUB_CLIENT_PORT:-8002}:8000"
    volumes:
      - type: bind
        source: ./contrib/oauth-client-example
        target: /srv/app
        consistency: cached
    depends_on:
      - web
